[workspace]

members = [
    "scene",
    "game_core",
    "physics",
    "math",
    "windowing",
    "render",
    "input",
    "game",
    "debug"
]

[profile.dev.package.render]
opt-level = 1
[profile.dev.package.vulkano]
opt-level = 1